<a href="https://colab.research.google.com/github/sagnik765/Image-Classifier/blob/main/Image_Classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install bing-image-downloader

In [2]:
!pip install ipython-autotime
%load_ext autotime

time: 732 µs (started: 2021-09-02 23:57:15 +00:00)


In [3]:
!mkdir images
from bing_image_downloader import downloader
downloader.download("animal cat", limit=10,  output_dir='images', adult_filter_off=True)

[%] Downloading Images to /content/images/animal cat


[!!]Indexing page: 1

[%] Indexed 10 Images on Page 1.


[%] Downloading Image #1 from https://i.pinimg.com/originals/80/60/81/806081f8fcf88dafda97b1c93a544862.jpg
[%] File Downloaded !

[%] Downloading Image #2 from https://pbs.twimg.com/media/DrqRyLAVsAA1SJo.jpg:large
[%] File Downloaded !

[%] Downloading Image #3 from https://i.pinimg.com/originals/32/88/e5/3288e5754990ffba38a13fa78bc980a0.jpg
[%] File Downloaded !

[%] Downloading Image #4 from https://i.pinimg.com/originals/27/1f/e1/271fe165279eff5edc72d758653fc0f3.jpg
[%] File Downloaded !

[%] Downloading Image #5 from https://i.pinimg.com/736x/69/8d/22/698d225ac0433f4aa116fb4116820e04.jpg
[%] File Downloaded !

[%] Downloading Image #6 from https://www.catsluvus.com/wp-content/uploads/2020/05/84157244_818202755326294_4149904901160484643_n.jpg
[%] File Downloaded !

[%] Downloading Image #7 from https://i.pinimg.com/originals/bf/0b/0c/bf0b0c44b3045b75d1b0f89f3e762a5f.jpg
[%

In [4]:
downloader.download("animal dog", limit=10,  output_dir='images', adult_filter_off=True)

[%] Downloading Images to /content/images/animal dog


[!!]Indexing page: 1

[%] Indexed 10 Images on Page 1.


[%] Downloading Image #1 from https://i.pinimg.com/originals/f4/6a/34/f46a3429885c8143b8830a2e76d249bb.jpg
[%] File Downloaded !

[%] Downloading Image #2 from https://i.pinimg.com/originals/dc/bc/d9/dcbcd967e5dd9cd290b789f1a51a9c73.jpg
[%] File Downloaded !

[%] Downloading Image #3 from http://www.dogshaming.com/wp-content/uploads/2014/06/image.jpg
[%] File Downloaded !

[%] Downloading Image #4 from https://i.pinimg.com/originals/57/ea/97/57ea97d7888a57336df836966991b558.jpg
[%] File Downloaded !

[%] Downloading Image #5 from https://i.pinimg.com/originals/a2/79/53/a279539f6d5049b1068716e0043cda16.jpg
[%] File Downloaded !

[%] Downloading Image #6 from https://i.pinimg.com/originals/f9/fa/8f/f9fa8fc5f725d5a205757e52fcaa572f.jpg
[%] File Downloaded !

[%] Downloading Image #7 from https://i.pinimg.com/originals/18/1d/f2/181df21816a9e943cc9f6ff0cd0e6476.jpg
[%] File Downlo

In [5]:
downloader.download("cars", limit=10,  output_dir='images', adult_filter_off=True)

[%] Downloading Images to /content/images/cars


[!!]Indexing page: 1

[%] Indexed 10 Images on Page 1.


[%] Downloading Image #1 from https://external-preview.redd.it/pbEfLIYe90hFmJFBXWG8K0oXU4ayUl-6-USZlF7G_qk.jpg?auto=webp&amp;s=b2d9b17a5a84826506058e26ddbaeead84d0761a
[!] Issue getting: https://external-preview.redd.it/pbEfLIYe90hFmJFBXWG8K0oXU4ayUl-6-USZlF7G_qk.jpg?auto=webp&amp;s=b2d9b17a5a84826506058e26ddbaeead84d0761a
[!] Error:: HTTP Error 403: Forbidden
[%] Downloading Image #1 from https://i.pinimg.com/originals/e8/5a/6c/e85a6cff5b06a5e2a0b94c0f539789a3.jpg
[%] File Downloaded !

[%] Downloading Image #2 from https://i.pinimg.com/originals/d2/ad/d6/d2add6400c95271ff439dc3f4c4f84f3.jpg
[%] File Downloaded !

[%] Downloading Image #3 from http://jaikrishnaamaruti.com/uploads/truevalue_cars/0_15-10-2020_09-58-23.jpeg
[%] File Downloaded !

[%] Downloading Image #4 from https://media.whatcar.com/migration/article_inline/fa3f2b3925370291872ddcf823dd8719749dcae6.jpg
[%] File Down

In [7]:
import os
import matplotlib.pyplot as plt
import numpy as np
from skimage.io import imread
from skimage.transform import resize

target = []
images = []
flat_data = []

DATADIR = "/content/images/cars"
CATEGORIES = ['animal cat','animal dog','car']

for category in CATEGORIES:
  class_num = CATEGORIES.index(category)
  path = os.path.join(DATADIR) #create path to use all images
  print(path)
  dirs = os.listdir(path)
  for img in dirs:
    img_array = imread(os.path.join(path,img))
    #print(img_array.shape)
    #plt.imshow(img_array)
    img_resized=resize(img_array,(150,150,3))
    flat_data.append(img_resized.flatten())
    images.append(img_resized)
    target.append(class_num)

flat_data=np.array(flat_data)
target = np.array(target)
images = np.array(images)

/content/images/cars
/content/images/cars
/content/images/cars
time: 14.5 s (started: 2021-09-03 00:00:07 +00:00)


In [8]:
#splitting data into train and test
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(flat_data,target,test_size=0.3,random_state=109)

time: 205 ms (started: 2021-09-03 00:00:45 +00:00)


In [9]:
from sklearn.model_selection import GridSearchCV
from sklearn import svm
param_grid = [
              {'C':[1,10,100,1000],'kernel':['linear']},
              {'C':[1,10,100,1000],'gamma':[0.001,0.0001],'kernel':['rbf']},
]

svc = svm.SVC(probability=True)
clf = GridSearchCV(svc,param_grid)
clf.fit(x_train,y_train)

GridSearchCV(cv=None, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=True, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid=[{'C': [1, 10, 100, 1000], 'kernel': ['linear']},
                         {'C': [1, 10, 100, 1000], 'gamma': [0.001, 0.0001],
                          'kernel': ['rbf']}],
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

time: 11.1 s (started: 2021-09-03 00:00:59 +00:00)


In [10]:
y_pred = clf.predict(x_test)
y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1])

time: 28.3 ms (started: 2021-09-03 00:01:21 +00:00)


In [11]:
y_test

array([2, 0, 2, 0, 0, 0, 2, 0, 1])

time: 7.52 ms (started: 2021-09-03 00:01:37 +00:00)


In [12]:
from sklearn.metrics import accuracy_score,confusion_matrix
accuracy_score(y_pred,y_test)

0.1111111111111111

time: 5.88 ms (started: 2021-09-03 00:01:51 +00:00)


In [13]:
confusion_matrix(y_pred,y_test)

array([[0, 0, 0],
       [5, 1, 3],
       [0, 0, 0]])

time: 10.3 ms (started: 2021-09-03 00:02:14 +00:00)
